### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by santirestrepo** [milankamilya/AccordianView#1]
I can't use it with Swift3, I tried to translate it to Swift 3 but it does not work

**Comment by Antilopez** [comment]
I made it work on Swift 3 by letting the automatic transformation made by xcode and also changing all castings of arrayOfBool's values from "as AnyObject" to "as! NSNumber".

This is my final code working on Swift 3, hope it helps:
[MKAccordionView.txt](https://github.com/milankamilya/AccordianView/files/518641/MKAccordionView.txt)

**Comment by santirestrepo** [comment]
@Antilopez I going to test it... Thanks for your help.

**Comment by milankamilya** [comment]
Thanks @santirestrepo  & @Antilopez
I have updated the repo. Thanks @Antilopez for the solution.
