### ISSUE TITLE
did select row at index path not working

### ISSUE THREAD

**Issue by mdcoder1** [milankamilya/AccordianView#3]
I tried implementing          func accordionView(_ accordionView: AccordionView, didSelectRowAt indexPath: IndexPath) {} but this method is not being called>
How do I get the selected row

**Comment by milankamilya** [comment]
Hi @mdcoder1 , Thanks for raising the issue. I have fixed that. The changes are available in master branch itself.

Please feel free to ask for any feature you need in AccordianView.

**Comment by mdcoder1** [comment]
Thank you.Its a great project!!

**Comment by milankamilya** [comment]
Thanks @mdcoder1 , please star & share!!
